"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "../../lib/supabase/client";

type Organization = { id: string; name: string; slug: string; business_type: string | null; phone: string | null; email: string | null; address: string | null; timezone: string | null; plan_code: string | null; implementation_status: string | null; subscription_status: string | null; agent_version: string | null; created_at: string; };
const fallback = "Não informado";
function slugify(value: string) { return value.normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
function statusLabel(value: string | null) { return ({ production: "Em produção", approved: "Aprovada", homologation: "Homologação", configuration: "Configuração", onboarding: "Onboarding", paused: "Pausada" } as Record<string, string>)[value || ""] || value || fallback; }
function organizationLabel(value: string | null) { return value || fallback; }

export default function OrganizationsLive() { const supabase = useMemo(() => createClient(), []); const [items, setItems] = useState<Organization[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [modal, setModal] = useState<Organization | "new" | null>(null); const [notice, setNotice] = useState("");
  async function load() { setLoading(true); setError(""); const { data, error } = await supabase.from("organizations").select("*").order("created_at", { ascending: false }); if (error) { console.error(error); setError("Não foi possível carregar as organizações."); } else setItems((data || []) as Organization[]); setLoading(false); }
  useEffect(() => { load(); }, []);
  const filtered = items.filter((item) => `${item.name} ${item.business_type || ""}`.toLowerCase().includes(query.toLowerCase()));
  return <><section className="page-heading"><div><div className="eyebrow">RanTech Agents</div><h1>Organizações</h1><p className="subtitle">Dados reais do Supabase · gestão de implantação e agentes.</p></div><button className="primary-button" onClick={() => setModal("new")}>+ Nova organização</button></section><div className="toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar organizações..." /><select defaultValue="all"><option value="all">Todos os status</option><option value="production">Em produção</option><option value="onboarding">Onboarding</option></select><button className="secondary-button" onClick={load}>Atualizar</button></div>{notice && <div className="auth-success inline-notice">{notice}</div>}{loading ? <article className="panel loading-state"><div className="skeleton-line"/><div className="skeleton-line short"/><div className="skeleton-table"/></article> : error ? <article className="panel empty-state"><div className="empty-icon">!</div><h2>{error}</h2><p>Confira a sessão e as permissões da sua conta.</p><button className="secondary-button" onClick={load}>Tentar novamente</button></article> : filtered.length === 0 ? <article className="panel empty-state"><div className="empty-icon">◈</div><h2>Nenhuma organização cadastrada</h2><p>Crie sua primeira organização para começar.</p><button className="primary-button" onClick={() => setModal("new")}>+ Nova organização</button></article> : <article className="panel"><div className="table-wrap"><table className="table"><thead><tr><th>Organização</th><th>Segmento</th><th>Implantação</th><th>Assinatura</th><th>Plano</th><th>Agente</th><th>Criação</th><th/></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><a className="table-link" href={`/organizations/${item.id}`}>{item.name}</a></td><td>{organizationLabel(item.business_type)}</td><td><span className="badge blue">{statusLabel(item.implementation_status)}</span></td><td>{organizationLabel(item.subscription_status)}</td><td>{organizationLabel(item.plan_code)}</td><td>{organizationLabel(item.agent_version)}</td><td>{new Date(item.created_at).toLocaleDateString("pt-BR")}</td><td><button className="text-button" onClick={() => setModal(item)}>Editar</button></td></tr>)}</tbody></table></div></article>}{modal && <OrganizationForm value={modal === "new" ? null : modal} onClose={() => setModal(null)} onSaved={(saved, created) => { setItems((current) => created ? [saved, ...current] : current.map((item) => item.id === saved.id ? saved : item)); setModal(null); setNotice(created ? "Organização criada com sucesso." : "Organização atualizada com sucesso."); setTimeout(() => setNotice(""), 3500); }} supabase={supabase} />}</>; }

function OrganizationForm({ value, onClose, onSaved, supabase }: { value: Organization | null; onClose: () => void; onSaved: (value: Organization, created: boolean) => void; supabase: ReturnType<typeof createClient> }) { const [form, setForm] = useState({ name: value?.name || "", business_type: value?.business_type || "Barbearia", phone: value?.phone || "", email: value?.email || "", address: value?.address || "", timezone: value?.timezone || "America/Sao_Paulo" }); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); const payload = { ...form, slug: value?.slug || slugify(form.name) }; const result = value ? await supabase.from("organizations").update(payload).eq("id", value.id).select().single() : await supabase.from("organizations").insert(payload).select().single(); if (result.error) { console.error(result.error); setError("Não foi possível salvar. Verifique as permissões da sua conta."); } else onSaved(result.data as Organization, !value); setSaving(false); } return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal panel" onMouseDown={(event) => event.stopPropagation()}><div className="panel-heading"><div><div className="eyebrow">Cadastro seguro</div><h2>{value ? "Editar organização" : "Nova organização"}</h2></div><button className="icon-button" onClick={onClose}>×</button></div><form className="settings-form" onSubmit={submit}>{[["name", "Nome da empresa *"], ["business_type", "Segmento *"], ["phone", "WhatsApp / telefone"], ["email", "E-mail"], ["address", "Endereço"], ["timezone", "Timezone"]].map(([key, label]) => <label key={key}>{label}{key === "business_type" ? <select value={form.business_type} onChange={(event) => setForm({ ...form, business_type: event.target.value })}><option>Barbearia</option><option>Oficina mecânica</option><option>Outro</option></select> : <input required={key === "name"} type={key === "email" ? "email" : "text"} value={form[key as keyof typeof form]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} />}</label>)}{error && <div className="auth-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving}>{saving ? "Salvando..." : "Salvar organização"}</button></div></form></div></div>; }
