"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { createClient } from "../../../lib/supabase/client";

const labels: Record<string, string> = { onboarding: "Em implantação", configuration: "Configuração", testing: "Em teste", homologation: "Homologação", approved: "Aprovada", production: "Em produção", paused: "Pausada", cancelled: "Cancelada", pending: "Pendente", active: "Ativa", past_due: "Em atraso", suspended: "Suspensa" };
const phone = (value: string) => { const d = value.replace(/\D/g, ""); return d.length === 11 ? `(${d.slice(0, 2)}) ${d.slice(2, 7)}-${d.slice(7)}` : d.length === 10 ? `(${d.slice(0, 2)}) ${d.slice(2, 6)}-${d.slice(6)}` : value; };

export default function OrganizationLiveDetail() { const { id } = useParams<{ id: string }>(); const [organization, setOrganization] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { createClient().from("organizations").select("*").eq("id", id).single().then(({ data, error: e }) => { if (e) setError("Não foi possível carregar esta organização."); else setOrganization(data); setLoading(false); }); }, [id]); if (loading) return <article className="panel loading-state">Carregando organização...</article>; if (error || !organization) return <article className="panel empty-state"><h2>{error || "Organização não encontrada"}</h2><Link className="secondary-button" href="/organizations">Voltar para organizações</Link></article>; return <section className="page-section"><div className="back-link"><Link href="/organizations">← Voltar para organizações</Link></div><section className="detail-header"><div><div className="eyebrow">Organização real</div><h1>{organization.name}</h1><p className="subtitle">{organization.business_type || "Não informado"} · {organization.email || "Sem e-mail"}</p></div><div className="detail-badges"><span className="badge blue">{organization.plan_code || "Plano não informado"}</span><span className="badge green">{labels[organization.implementation_status] || organization.implementation_status || "Status não informado"}</span></div></section><div className="metric-grid detail-metrics"><article className="metric-card"><span className="metric-top">Telefone</span><strong>{organization.phone ? phone(organization.phone) : "Não informado"}</strong></article><article className="metric-card"><span className="metric-top">Assinatura</span><strong>{labels[organization.subscription_status] || organization.subscription_status || "Não informado"}</strong></article><article className="metric-card"><span className="metric-top">Agente</span><strong>{organization.agent_version || "Não configurado"}</strong></article></div><article className="panel detail-panel"><div className="panel-heading"><div><h2>Dados da organização</h2><p>{organization.address || "Endereço não informado"}</p></div><Link className="secondary-button" href="/organizations">Editar pela listagem</Link></div><div className="detail-grid"><div><span className="eyebrow">Slug</span><h3>{organization.slug}</h3><p>Timezone: {organization.timezone || "Não informado"}</p></div><div><span className="eyebrow">Criada em</span><h3>{new Date(organization.created_at).toLocaleDateString("pt-BR")}</h3><p>Os demais módulos continuam mockados.</p></div></div></article></section>; }
