"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../lib/supabase/client";

export function AuthShell({ children }: { children: React.ReactNode }) { return <main className="auth-page"><div className="auth-card"><div className="auth-brand"><img src="/brand/symbol-light.svg" alt="RanTech" /><div><strong>RanTech</strong><span>AGENTES PLATFORM</span></div></div>{children}<small className="auth-footnote">Ambiente protegido RanTech Agents</small></div></main>; }

export function LoginForm() { const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); const { error } = await createClient().auth.signInWithPassword({ email, password }); if (error) setError("Não foi possível entrar. Verifique e-mail e senha."); else router.replace("/dashboard"); setLoading(false); } return <><div className="auth-heading"><div className="eyebrow">Bem-vindo de volta</div><h1>Entrar na plataforma</h1><p>Acesse o painel da sua operação.</p></div><form className="auth-form" onSubmit={submit}><label>E-mail<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="voce@empresa.com" /></label><label>Senha<input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Sua senha" /></label>{error && <div className="auth-error">{error}</div>}<button className="primary-button" disabled={loading}>{loading ? "Entrando..." : "Entrar"}</button></form><a className="auth-link" href="/forgot-password">Esqueci minha senha</a></>; }

export function ForgotForm() { const [email, setEmail] = useState(""); const [sent, setSent] = useState(false); const [error, setError] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); setError(""); const { error } = await createClient().auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/reset-password` }); if (error) setError("Não foi possível enviar o e-mail agora."); else setSent(true); } return <><div className="auth-heading"><div className="eyebrow">Recuperação</div><h1>Esqueceu sua senha?</h1><p>Enviaremos um link seguro para redefinir seu acesso.</p></div>{sent ? <div className="auth-success">Se o e-mail estiver cadastrado, você receberá as instruções em instantes.</div> : <form className="auth-form" onSubmit={submit}><label>E-mail<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="voce@empresa.com" /></label>{error && <div className="auth-error">{error}</div>}<button className="primary-button">Enviar link</button></form>}<a className="auth-link" href="/login">Voltar para o login</a></>; }

export function ResetForm() { const router = useRouter(); const [password, setPassword] = useState(""); const [error, setError] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); const { error } = await createClient().auth.updateUser({ password }); if (error) setError("Não foi possível atualizar a senha."); else router.replace("/dashboard"); } return <><div className="auth-heading"><div className="eyebrow">Novo acesso</div><h1>Redefinir senha</h1><p>Escolha uma senha segura para sua conta.</p></div><form className="auth-form" onSubmit={submit}><label>Nova senha<input type="password" minLength={8} required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Mínimo de 8 caracteres" /></label>{error && <div className="auth-error">{error}</div>}<button className="primary-button">Salvar nova senha</button></form></>; }
