"use client";

import { useState } from "react";
import { agents, organizations, services } from "../mocks/data";

export default function OrganizationDetail({ id }: { id: string }) {
  const organization = organizations.find((item) => item.id === id) || organizations[0];
  const agent = agents.find((item) => item.organization === organization.name);
  const [tab, setTab] = useState("Visão geral");
  return <div className="organization-detail"><div className="back-link"><a href="/organizations">← Voltar para organizações</a></div><section className="detail-header"><div><div className="eyebrow">Organização</div><h1>{organization.name}</h1><p className="subtitle">{organization.segment} · desde {organization.created}</p></div><div className="detail-badges"><span className="badge blue">{organization.plan}</span><span className="badge green">{organization.status}</span></div></section><nav className="detail-tabs">{["Visão geral", "Agente", "Clientes", "Conversas", "Agenda", "Serviços", "Conhecimento", "Configurações"].map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</nav><section className="metric-grid detail-metrics"><article className="metric-card"><span className="metric-top">Agente configurado</span><strong className="detail-value">{agent?.name || organization.agent}</strong><span className="metric-delta">{agent?.version || organization.version}</span></article><article className="metric-card"><span className="metric-top">Homologação</span><strong className="detail-value">{organization.homologation}</strong><span className="metric-delta">Status do onboarding</span></article><article className="metric-card"><span className="metric-top">Plano atual</span><strong className="detail-value">{organization.plan}</strong><span className="metric-delta">Assinatura simulada</span></article></section><article className="panel detail-panel"><div className="panel-heading"><div><h2>{tab}</h2><p>Informações simuladas de {organization.name}.</p></div><button className="secondary-button">Editar</button></div>{tab === "Agente" ? <div className="detail-grid"><div><span className="eyebrow">Agente principal</span><h3>{agent?.name || organization.agent}</h3><p>Modelo: {agent?.model || "GPT-4o mini"}</p></div><div><span className="eyebrow">Última atividade</span><h3>{agent?.activity || "Ainda não iniciado"}</h3><p>Versão publicada: {agent?.version || organization.version}</p></div></div> : tab === "Serviços" ? <div className="detail-grid">{services.filter((item) => item.organization === organization.name).map((service) => <div className="mini-card" key={service.name}><strong>{service.name}</strong><span>{service.price} · {service.duration}</span></div>)}<div className="mini-card"><strong>Catálogo da organização</strong><span>Dados mock para revisão visual</span></div></div> : <div className="detail-grid"><div><span className="eyebrow">Responsável</span><h3>RanTech Admin</h3><p>Acompanhamento de implantação</p></div><div><span className="eyebrow">Próximo passo</span><h3>Revisar dados</h3><p>Nenhuma ação real é executada nesta etapa.</p></div></div>}</article></div>;
}
